import { Component, OnInit, TemplateRef } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { BsModalRef, BsModalService } from 'ngx-bootstrap/modal';
import { map } from 'rxjs/operators';
import { Complaint } from 'src/app/models/complaint';
import { ComplaintService } from 'src/app/services/complaint.service';
import * as _ from 'lodash';

@Component({
  selector: 'app-complaints-list',
  templateUrl: './complaints-list.component.html',
  styleUrls: ['./complaints-list.component.css']
})
export class ComplaintsListComponent implements OnInit {

  Complaints? : Complaint[];
  currentComplaint? : Complaint;
  currentIndex = -1;
  selectedcomplaintType = '';
  selectedComplaint? : Complaint[];
  searchText = '';
  selectedGRP = 'HWH-GRP';
  selectedPriority = 'Critical';
  selectedRemarks = '';
  order: any;
  showData: any;
  p:number = 1;
  loader = true;
  modalRef!: BsModalRef;
  modalComplaint? : String = '';
  modalComplaint_progress_unId? : String = '';
  modalComplaint_progress_status? : string = '';
  modalComplaint_progress_priority? : String = '';
  message = '';
  key : string = 'timestamp';
  reverse : boolean = false;
  stn : string[] = [
            "Howrah R/S",
            "Tikiapara R/S",
            "Liluah R/S",
            "Belur Math R/S",
            "Belur R/S",
            "Bally R/S",
            "Bally Halt R/S",
            "Bally Ghat R/S",
            "Baranagar R/S ",
            "Dakhineswar R/S",
            "Rajchandrapur  R/S ",
            "Belanagar R/S",
            "Bhattanagar R/S",
            "Dankuni R/S",
            "Uttarpara R/S",
            "Hindmotor R/S",
            "Konnagar R/S",
            "Gobra R/S",
            "Janai Road R/S",
            "Begampur R/S",
            "Baruipara R/S",
            "Mirzapur Bankipur R/S",
            "Balarambati R/S",
            "Kamarkundu R/S",
            "Madhusudanpur R/S",
            "Chandanpur R/S",
            "Porabazar R/S",
            "Belmuri R/S",
            "Dhaniakhali Halt R/S",
            "Sibaichandi R/S",
            "Cheragram R/S",
            "Hazigarh R/S",
            "Gurap R/S",
            "Jhapandanga R/S",
            "Jaugram R/S",
            "Nabagram R/S",
            "Masagram R/S",
            "Chanchai R/S",
            "Pallaroad R/S",
            "Tarakeswar R/S",
            "Lokenath R/S",
            "Bahirkhanda R/S",
            "Kaikala R/S",
            "Haripal R/S",
            "Malia Halt  R/S",
            "Nalikul R/S",
            "Singur R/S ",
            "Nasibpur R/S",
            "Diara R/S",
            "Rishra R/S,",
            "Serampore R/S,",
            "Sheoraphully R/S",
            "Baidyabati R/S",
            "Bhadreswar R/S",
            "Mankundu R/S",
            "Chandannagr R/S",
            "Chinsurah R/S",
            "Hooghly R/S",
            "Bandel R/S",
            "Hooghly Ghat R/S",
            "Garifa R/S ",
            "Bansberia R/S",
            "Tribeni R/S",
            "Islampara Halt R/S",
            "Adisaptagram R/S",
            "Magra R/S",
            "Talandu R/S",
            "Khanyan R/S",
            "Pandua R/S",
            "Simlagarh R/S ",
            "Bainchi Gram R/S",
            "Bainchi R/S",
            "Debipur R/S",
            "Bagila R/S",
            "Memari R/S",
            "Nimo R/S",
            "Rasulpur R/S",
            "Palsit R/S",
            "Saktigarh R/S",
            "Gangpur R/S",
            "Barddhaman Jn. R/S",
            "Talit R/S",
            "Khana Junction R/S",
            "Galsi R/S",
            "Paraj R/S",
            "Mankar R/S",
            "Jhapater Dhal R/S",
            "Banpas R/S",
            "Noadar Dhal R/S",
            "Guskara R/S",
            "Pichkurirdhal R/S",
            "Bhedia R/S",
            "Kamnara R/S",
            "Kshetia R/S",
            "Chamardighi R/S",
            "Karjana R/S",
            "Karjanagram R/S",
            "Amarun R/S",
            "Bhatar R/S",
            "Balgona R/S",
            "Panagarh R/S",
            "Rajbandh R/S",
            "Durgapur R/S",
            "Waria R/S",
            "Pandabeswar R/S",
            "Ukhra R/S",
            "Andal R/S",
            "Kajoragram R/S",
            "Sidhuli R/S",
            "Ikrah R/S",
            "Jamuria R/S",
            "Baraboni R/S",
            "Sonachara R/S",
            "Tapasi R/S",
            "Bhaktarnagar Halt R/S",
            "Raniganj R/S",
            "Nimcha Halt R/S",
            "Barachak R/S",
            "Kalipahari R/S",
            "Asansol R/S",
            "Burnpur R/S",
            "Damodar R/S",
            "Sitarampur R/S",
            "Kulti R/S",
            "Barakar R/S",
            "Salanpur R/S",
            "Rupnarayanpur R/S",
            "Kuntighat R/S",
            "Dumurdaha R/S",
            "Khamargachi R/S",
            "Jirat R/S",
            "Balagarh R/S",
            "Somrabazar R/S",
            "Behula R/S",
            "Guptipara R/S",
            "Ambika Kalna R/S ",
            "Baghnapara R/S",
            "Dhatrigram R/S",
            "Nandai Gram Halt R/S",
            "Samudragarh R/S",
            "Kalinagar R/S",
            "Nabadwip Dham R/S",
            "Bishnupriya Halt R/S",
            "Bhandertikuri R/S",
            "Purbasthali R/S",
            "Mertala Phaleya Halt R/S",
            "Lakshmipur R/S",
            "Belerhat Halt R/S",
            "Patuli R/S",
            "Agradwip R/S",
            "Sahebtala Halt R/S",
            "Dainhat R/S",
            "Katwa R/S",
            "Shripat Shrikhand R/S",
            "Srikhanda R/S",
            "Bankapasi R/S",
            "Kaichar R/S",
            "Nigan R/S",
            "Saota R/S",
            "Nabagram Kakurhati Halt R/S",
            "Shiblun Halt R/S",
            "Gangatikuri R/S",
            "Ambalgram R/S",
            "Pachandi R/S",
            "Nirol Gram R/S",
            "Nirol R/S",
            "Komarpur R/S",
            "Jnandas Kandra R/S",
            "Kurmadanga R/S",
            "Jhamatpur Baharan R/S",
            "Salar R/S",
            "Malihati Talibpur R/S",
            "Tenya R/S",
            "Miangram R/S",
            "Bazarsau R/S",
            "Kazipara Halt R/S",
            "Chowrigacha R/S",
            "Daskalgram R/S",
            "Kirnahar R/S",
            "Maheshpur R/S",
            "Labpur R/S",
            "Gopalpurgram R/S",
            "Chowhatta R/S",
            "Ahmadpur R/S",
            "Bolpur R/S",
            "Prantik R/S",
            "Kopai R/S",
            "Ahmedpur R/S ",
            "Bataspur R/S",
            "Sainthia R/S",
            "Gadadharpur R/S",
            "MollarpurR/S",
            "Tarapith Road R/S",
            "Rampurhat R/S ",
            "Swadhinpur R/S",
            "Adalpahari R/S ",
            "Nalhati R/S",
            "Chatra R/S",
            "Murarai R/S",
            "Banshlai Bridge R/S",
            "Rajgram R/S",
            "Lohapur R/S",
            "Takipur R/S",
            "Mahisadohari R/S",
            "Kunuri R/S",
            "Suri R/S",
            "Kachujor R/S",
            "Chinpai R/S",
            "Dubrajpur R/S",
            "Panchra R/S",
            "Bhimgara R/S",
            "Kanthialia Road R/S",
            "Karnasubarna R/S",
            "Jibanti Halt R/S",
            "Khagraghat Road R/S",
            "Niyalishpara Halt R/S",
            "Lalbaghcourt Road R/S",
            "Dahaparadham Halt R/S",
            "Azimganj Jn R/S",
            "Azimganj City R/S",
            "Gosaingram R/S",
            "Barala R/S",
            "Sagardighi R/S",
            "Morgram R/S",
            "Poradanga R/S",
            "Mohipal Road R/S",
            "Mohipal Halt R/S",
            "Noapara Mahisasur Halt R/S",
            "Monigram R/S",
            "Gankar R/S",
            "Jangipore Road R/S",
            "Ahiran Halt R/S",
            "Sujnipara R/S",
            "Nimtita R/S",
            "Basudebpur Halt R/S",
            "Dhulianganga R/S",
            "Sankopara Halt R/S",
            "Ballalpur Halt R/S",
            "",
            "Sealdah R/S",
            "Park Circus R/S",
            "Bidhannagar R/S",
            "Sir Gurudas Banerjee Halt",
            "Dum Dum Jn.",
            "Dum Dum Cantt.",
            "Jessore Road",
            "Biman Bandar",
            "Belgharia",
            "Agarpara",
            "Sodpur",
            "Khardaha",
            "Titagarh",
            "Barrackpore",
            "Patipukur",
            "Kolkata Terminal",
            "Tala",
            "Bag Bazar",
            "Sovabazar",
            "Bara Bazar",
            "B.B.D. Bag",
            "Eden Gardens",
            "Prinsepghat",
            "Khidirpur",
            "Re-mount Road",
            "Palta",
            "Ichhapur",
            "Shyamnagar",
            "Jagaddal",
            "Kankinara",
            "Naihati Junction",
            "Halisahar",
            "Kanchrapara Workshop Gate",
            "Kanchrapara",
            "Kalyani",
            "Kalyani Shilpanchal",
            "Kalynai Ghoshpara",
            "Kalyani Simanta",
            "Madanpur",
            "Simurali",
            "Palpara",
            "Chakdaha",
            "Payradanga",
            "Ranaghat Junction",
            "Kalinarayanpur Jn.",
            "Habibpur",
            "Phulia",
            "Bathna Krittibas",
            "Santipur",
            "Bankimnagar",
            "Panchberia",
            "Aranghata",
            "Bahirgachhi",
            "Bhayna Halt",
            "Santinagar Halt",
            "Bagula",
            "Mayurhat Halt",
            "Taraknagar Halt",
            "Majdhia",
            "Banpur",
            "Harisnagar",
            "Gede",
            "Birnagar",
            "Taherpur",
            "Badkulla",
            "Jalalkhali Halt",
            "Krishnanagar City Jn.",
            "Dignagar Halt",
            "Bahadurpur halt",
            "Dhubulia",
            "Muragachha",
            "Bethuadahari",
            "Sonadanga",
            "Debogram",
            "Paglachandi",
            "Plassey",
            "Sirajnagar Halt",
            "Reginagr",
            "Beldanga",
            "Bhabta",
            "Sargachhi",
            "Balarampur Halt",
            "Berhampore Court",
            "Cossembazar",
            "Murshidabad",
            "Jiaganj",
            "Subarnamigi",
            "Bhagabangola",
            "Pirtala",
            "Krishnapur",
            "Lalgola",
            "Bamangachhi",
            "Duttapukur",
            "Bira",
            "Guma",
            "Ashoknagar Road",
            "Habra",
            "Sanhati Halt",
            "Machlandapur",
            "Gobardanga",
            "Thakurnagar",
            "Chandpara",
            "Bibhuti Bhushan Halt",
            "Bongaon",
            "Satberia",
            "Petrapole",
            "Coopers Halt",
            "Naba Raynagar",
            "Gagnapur",
            "Majhergram",
            "Akipur",
            "Gopalnagar",
            "Durganagar",
            "Birati",
            "Bisharpara Kodaliya",
            "New Barrackpore",
            "Madhyamgram",
            "Hridaypur",
            "Barasat Jn.",
            "Kazipara",
            "Karea Kadambagachhi",
            "Bahira Kalibari",
            "Sandalia",
            "Beliaghata Road",
            "Lebutala",
            "Bhasila",
            "Harua Road",
            "Kankra Mirzanagar",
            "Malatipur",
            "Ghoraras Ghona",
            "Champapukur",
            "Bhyabla",
            "Basirhat",
            "Matania Anantapur",
            "Madhyampur",
            "Nimdanri",
            "Taki road",
            "Hasnabad",
            "Ballygunge Jn.",
            "Dhakuria",
            "Lake Gardens",
            "Tollygunge",
            "New Alipur",
            "Majherhat",
            " Brace Bridge",
            "Santoshpur",
            "Akra",
            "Nungi",
            "Budge Budge",
            "Jadavpur",
            "Baghajatin",
            "New Garia",
            "Garia",
            "Narendrapur",
            "Sonarpur Jn.",
            "Subhasgram",
            "Mallickpur",
            "Bidyadharpur",
            "Kalikapur",
            "Champahati",
            "Piali",
            "Gourdaha",
            "Ghutiari Sarif",
            "Betberia Ghola",
            "Taldi",
            "Matla",
            "Canning",
            "Baruipur Jn.",
            "Kalyanpur",
            "Shasan Road",
            "Krishna Mohan",
            "Dhapdhapi",
            "Suryapur",
            "Gocharan",
            "Hogla",
            "Dakshin Barasat",
            "Baharu",
            "Joynagar-Majhilpur",
            "Mathurapur",
            "Madhabpur",
            "Lakshmikantapur",
            "Udairampur",
            "Kulpi",
            "Karanjali",
            "Nischindapur Market Halt",
            "Nischindapur",
            "Kashinagar",
            "Madhabnagar Halt",
            "Kakdwip",
            "Ukilerhat",
            "Namkhana",
            "Dakshin Durgapur",
            "Hotor",
            "Dhamuah",
            "Uttar Radhanagar",
            "Magrahat",
            "Bahirpuya Halt",
            "Sangrampur",
            "Deula",
            "Netra",
            "Basuldabga",
            "Gurudas Nagar",
            "Diamond Harbour",
            "Tildanga Rly. Station",
            "New Farakka Rly. Station ",
            "Chama gram Rly. Station ",
            "Khaltipur Rly. Station ",
            "Jamairghata Rly. Station ",
            "Gour Malda Rly. Station ",
            "Malda town Rly. Station  ",
            "Old Malda Jn. Rly. Station ",
            "Adina Rly. Station ",
            "Eklakhi Rly. Station ",
            "Mahananda bridge Halt Rly. Station  ",
            "Kumarganj Rly. Station ",
            "Sripur Halt Rly. Station ",
            "Samsi Rly. Station ",
            "Malahar Halt Rly. Station ",
            "Bhaluka Road Rly. Station ",
            "Milan Garh Rly. Station ",
            "Harishchandrapur Rly. Station ",
            "Kumedpur Rly. Station  ",
            "Dalkhola Rly. Station  ",
            "Surjakamal Rly. Station  ",
            "Kanki Rly. Station  ",
            "Hatwar Rly. Station ",
            "Panjipara Rly. Station  ",
            "Ikarchala Rly. Station  ",
            "Gaisal Rly. Station ",
            "Gunjaria Rly. Station ",
            "Aluabari Road Rly. Station  ",
            "Tinmile Hat Rly. Station  ",
            "Dumdangi Rly. Station  ",
            "Chatterhat Rly. Station  ",
            "Nijbari Rly. Station ",
            "Rangapani Rly. Station ",
            "New Jalpaiguri Rly. Station  ",
            "Ambari Falakata Rly. Station  ",
            "Belacoba Rly. Station  ",
            "Raninagar Rly. Station ",
            "Jalpaiguri Road Rly. Station ",
            "New Domohani Rly. Station  ",
            "New Maynaguri Rly. Station  ",
            "Betgara Rly. Station ",
            "Altagram Rly. Station  ",
            "Dhupguri Rly. Station ",
            "Kholaigram Rly. Station  ",
            "Salbari Rly. Station  ",
            "Falakata Rly. Station ",
            "Gumanihat Rly. Station  ",
            "Ghoksadanga Rly. Station ",
            "Sajerpar Rly. Station  ",
            "Pundibari Rly. Station  ",
            "New Cooch Behar Rly. Station  ",
            "New Baneswer Rly. Station  ",
            "New Alipurduar Rly. Station  ",
            "Samuktala Road Rly. Station ",
            "Kamakhyaguri Rly. Station  ",
            "Jorai Rly. Station  ",
            "Baneswar Rly. Station  ",
            "Alipurduar Rly. Station  ",
            "Alipurduar Court Rly. Station  ",
            "Alipurduar Jn. Rly. Station  ",
            "Coochbehar Rly. Station  ",
            "Dewanhat Rly. Station ",
            "Vetaguri Rly. Station ",
            "Dinhata College Halt Rly. Station  ",
            "Dinhata  Rly. Station  ",
            "Falimari Rly. Station ",
            "New Gitaldah Rly. Station  ",
            "Abutara Halt Rly. Station  ",
            "Bamanhat Rly. Station ",
            "Ambari Falakata Rly. Station  ",
            "Belacoba Rly. Station  ",
            "Raninagar Rly. Station ",
            "Jalpaiguri Road Rly. Station ",
            "Ambari Falakata Rly. Station  ",
            "Belacoba Rly. Station  ",
            "Raninagar Rly. Station ",
            "Mohitnagar Rly. Station ",
            "Jalpaiguri Rly. Station ",
            "Kadobari Halt Rly. Station ",
            "Mandalghat Rly. Station ",
            "Nandanpur Kererpara Halt. Rly. Station ",
            "Kashiabari Halt Rly. Station ",
            "Haldibari Rly. Station ",
            "Adhikari Rly. Station",
            "Batasi Rly. Station",
            "Naxalbari Rly. Station",
            "Hatighisa Rly. Station",
            "Bagdogra Rly. Station",
            "Matigara Rly. Station",
            "Siliguri Jn. Rly. Station",
            "Gulma Rly. Station",
            "Sevoke Rly. Station",
            "Bagrakote Rly. Station",
            "Odlabari Rly. Station",
            "Damdim Rly. Station",
            "New Mal Jn. Rly. Station",
            "Chalsa Jn. Rly. Station",
            "Nagarkata Rly. Station",
            "Carron Rly. Station",
            "Chengmari Rly. Station",
            "Banarhat Rly. Station",
            "Binnaguri Rly. Station",
            "Dalgaon  Rly. Station",
            "Mujnai Rly. Station",
            "Madarihat Rly. Station",
            "Hasimara Rly. Station  ",
            "Hamiltonganj Rly. Station ",
            "Kalchini Rly. Station  ",
            "Garopara Rly. Station ",
            "Rajabhatkhawa Rly. Station ",
            "Damanpur Rly. Station ",
            "Alipurduar jn. Rly. Station  ",
            "Alipurduar College  Rly. Station  ",
            "Salsalabari Rly. Station  ",
            "Samuktala Road Rly. Station ",
            "Kamakhyaguri Rly. Station  ",
            "Jorai Rly. Station  ",
            "Siliguri Town Rly. Station  ",
            "Jitkia Rly. Station ",
            "Raiganj Rly. Station ",
            "Bamangram Rly. Station ",
            "Bangalbari Rly. Station ",
            "Kaliaganj Rly. Station ",
            "Damilgaon Rly. Station ",
            "Radhikapur Rly. Station ",
            "Old Malda Jn. Rly. Station ",
            "Adina Rly. Station ",
            "Eklakhi Rly. Station ",
            "Gazole Rly. Station ",
            "Mahanagar Rly. Station ",
            "Deotala Rly. Station ",
            "Daulatpur Rly. Station ",
            "Buniadpur Rly. Station ",
            "Gangarampur Rly. Station ",
            "Malancha Rly. Station ",
            "Rampur bazar Rly. Station ",
            "Mallickpur Hat Rly. Station ",
            "Balurghat Rly. Station ",
            "Old Malda Jn. Rly. Station ",
            "Malda Court Rly. Station ",
            "Singhabad Rly. Station ",
            "Shalimar R/S ",
            "Padmapukhur R/S",
            "Dasnagar R/S",
            "Ramrajatala R/S",
            "Santragachi R/S",
            "Mourigram R/S",
            "Andul R/S",
            "Sankrail R/S",
            "Abada R/S",
            "Nalpur R/S",
            "Bauria R/S",
            "Chengail R/S",
            "Fuleswar R/S",
            "Uluberia R/S",
            "Birshibpur R/S",
            "Kulgachia R/S",
            "Bagnan R/S",
            "Ghoraghata R/S",
            "Deulti R/S",
            "Kolaghat R/S",
            "Mecheda R/S",
            "Nandai gajan R/S",
            "Bhogpur R/S",
            "Narayan Pakuria Murail R/S",
            "Panskura R/S",
            "Khirai Halt R/S",
            "Haur R/S",
            "Raghunathbari R/S",
            "Rajgoda R/S",
            "Sahid Matangini Halt R/S",
            "Tamluk R/S",
            "Keshabpur R/S",
            "Satish Samanta Halt R/S",
            "Mahisadal R/S",
            "Barda R/S",
            "Basulia Sutahata R/S",
            "Durgachak  R/S",
            "Durgachak Town Halt R/S",
            "Bandar Halt R/S",
            "Haldia R/S",
            "Nandakumar R/S",
            "Laban Satyagrah Smarak Halt R/S",
            "Deshapran R/S",
            "Henria Halt R/S",
            "Nachinda Halt R/S",
            "Kanthi R/S",
            "Shitalpur Halt R/S",
            "Sujalpur Halt R/S ",
            "Ashapurnadevi Halt R/S",
            "Badalpur Halt R/S",
            "Ramnagar R/S",
            "Tikra Halt R/S",
            "Digha R/S",
            "Radhamohanpur R/S",
            "Duan Halt R/S",
            "Balichak R/S",
            "Shyamchak R/S",
            "Madpur R/S",
            "Jakpur R/S",
            "Kharagpur R/S",
            "Hizli  R/S",
            "Benapur R/S",
            "Narayangarh R/S",
            "Bakrabad R/S",
            "Belda R/S",
            "Nekurshrini R/S",
            "Dantan R/S",
            "Angua R/S",
            "Nimpura Yard Halt R/S",
            "Kalaikunda R/S",
            "Girimaidan R/S",
            "Gokulpur R/S",
            "Cassai Halt R/S",
            "Midnapur R/S",
            "Khemashuli R/S",
            "Sardiha R/S",
            "Banshtola Halt R/S",
            "Jhargram R/S",
            "Khatkhura Halt R/S",
            "Gidhni R/S",
            "Bhadutola Halt  R/S",
            "Godapiyasal R/S",
            "Salboni R/S",
            "C.K.Road R/S",
            "Garbeta R/S",
            "Bogri Road Halt R/S",
            "Piyardoba R/S",
            "Bishnupur R/S",
            "Ramsagar R/S",
            "Ondagram R/S",
            "Kalisen Halt R/S",
            "Bheduasole Halt R/S",
            "Bankura R/S",
            "Anchuri Halt R/S",
            "Chatna R/S",
            "Jhantipahari R/S",
            "Bikna Halt R/S",
            "Nabanda Halt R/S",
            "Belboni Halt R/S",
            "Beliatore Halt R/S",
            "Chandar Halt R/S",
            "Brindabanpur Halt R/S",
            "Srirampur Halt R/S",
            "Hamirhati Halt R/S",
            "Sonamukhi R/S",
            "Dhansimla Halt R/S",
            "Dhagaria Halt R/S",
            "Patrasayar Halt R/S",
            "Betur Halt R/S",
            "Kumrul Halt R/S",
            "Indas Halt R/S",
            "Shankrul Halt R/S",
            "Sahaspur Halt R/S",
            "Bowaichandi Halt R/S",
            "Guir saranga Halt ",
            "Kaiyar Halt",
            "Sehara Bazar Halt,",
            "Gopinathpur Halt",
            "Shyamsundarpur Halt",
            "Rainagar Halt",
            "Srijam R/S",
            "Indrabil R/S",
            "Metal Sahar R/S",
            "Adra R/S",
            "Gardhrubeswar R/S",
            "Joychandi pahar R/S",
            "Bero R/S",
            "Ramkanali R/S",
            "Murardihi  R/S",
            "Madhukunda R/S",
            "Sanka R/S",
            "Rukni R/S",
            "Santaldihi R/S",
            "Anara R/S",
            "Bagalia R/S",
            "Kustaur R/S",
            "Chharrah R/S",
            "Purulia R/S",
            "Tamna R/S",
            "Kantadihi R/S",
            "Urma R/S",
            "Barabhum R/S",
            "Biramdih R/S",
            "Gourinath Dham R/S",
            "Chas Road Halt R/S",
            "Gar Jaipur Halt R/S",
            "Barbendia Halt R/S",
            "Kotsila R/S",
            "Begunkodar Halt  R/S",
            "Jhalda R/S",
            "Tulin R/S",
            "Damrughutu Halt R/S",
            "Pundag R/S",
            "Illoo R/S",
            "Torang R/S",
            "Suisa R/S"];

  //Demo purpose only, Data might come from Api calls/service
  name = 'Progress Bar';
  public counts = ["Recieved","Assigned","In Progress","Completed"];
  orderStatus?  = "";

  constructor(private complaintService : ComplaintService, private titleService : Title, private modalService : BsModalService) {
    this.titleService.setTitle("CivilIn-complaints-list");
   }

  ngOnInit(): void {
    setTimeout(()=>{
      this.loader=false;
    }, 2000);
    this.retrieveComplaint();
  }

  public retrieveComplaint() : void {
    this.complaintService.getAllComplaints().snapshotChanges().pipe(
      map(changes => 
        changes.map(c =>
          ({ key : c.payload.key, ...c.payload.val()})
        )
      )
    ).subscribe(data => {
      this.Complaints = data;

      // convert stn_details to station name

      this.Complaints.forEach( (element) => {
        console.log("stn_details " + element.stn_details);
        const n = element.stn_details;
        console.log("stn_details--->n " + n);
        
        element.stn_details_name = this.stn[n!];

        console.log("element.stn_details_name " + element.stn_details_name);
      })

      // convert trainPnr to station names

      this.Complaints.forEach( (element) => {
        var newarr = element.trainPnr!.split("|");
        const n1 = Number(newarr[0]);
        const n2 = Number(newarr[1]);
        console.log("n1 "+n1 + "n2 " + n2);
        element.stn_starting = this.stn[n1!];
        element.stn_ending = this.stn[n2!];
        console.log("element.stn_starting"+element.stn_starting);
        console.log("element.stn_ending"+element.stn_ending);

      })

      this.selectedComplaint = this.Complaints?.filter(
        item => item.status === 'Pending'
      );
    
      // by default recent complaint will show
      
      this.sortTimestamp(this.key);
    })
  }

  public valueSelected(){
    if(this.selectedcomplaintType === 'All')
    {
      this.selectedComplaint = this.Complaints;
      console.log("else" + this.selectedComplaint);
      console.log("Else selected head" + this.selectedcomplaintType);
    }
    else
    {
      this.selectedComplaint = this.Complaints?.filter(
        item => item.status === this.selectedcomplaintType
      );
      console.log("If" + this.selectedComplaint);
      console.log("If selected head" + this.selectedcomplaintType);
    }
  }

  public sort(key : string)
  {
    this.key=key;
    this.reverse = !this.reverse;
  }

  public sortTimestamp(key : string)
  {
    this.key=key;
    if(this.reverse == false){
      this.reverse = !this.reverse;
    }
    else{
      this.reverse = this.reverse;
    }
  }

  public openModal(template : TemplateRef<any>, complaint : Complaint)
  {
    sessionStorage.setItem('complaint_unId', JSON.stringify(complaint.complaintUnId));
    this.currentComplaint = complaint;
    this.modalComplaint = JSON.stringify(complaint.complaintUnId);
    this.modalRef = this.modalService.show(template);
  }

  public openModal_progress(template : TemplateRef<any>, complaint : Complaint)
  {
    // sessionStorage.setItem('assistance_progress_unId', JSON.stringify(assistance.assUnId));
    // sessionStorage.setItem('assistance_progress_status', JSON.stringify(assistance.status));
    // sessionStorage.setItem('assistance_progress_priority', JSON.stringify(assistance.priority));
    this.modalComplaint_progress_unId = JSON.stringify(complaint.complaintUnId);
    this.modalComplaint_progress_status = JSON.stringify(complaint.status);
    this.modalComplaint_progress_priority = JSON.stringify(complaint.priority);
    this.orderStatus = complaint.status;
    console.log("orderStatus "+this.orderStatus);
    this.modalRef = this.modalService.show(template);
  }

  public updateComplaint(): void {
    const data = {
      status: 'Assigned',
      assignedGRP: this.selectedGRP,
      priority: this.selectedPriority,
      remarks: this.selectedRemarks
      //description: this.currentTutorial.description
    };

    console.log(data);

    if (this.currentComplaint!.key) {
      this.complaintService.update(this.currentComplaint!.key, data)
        .then(() => this.message = 'The Complaint was updated successfully!')
        .catch(err => console.log(err));
    }

    sessionStorage.removeItem('complaint_unId');
    this.modalService.hide();
  }
}
